name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 'stable'
          - 'nightly'
        os:
          - 'ubuntu-latest'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: rust-${{ inputs.rust }}-os-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: fmt
        if: matrix.rust == 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: clippy
        if: matrix.rust == 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -r --all
